### ISSUE TITLE
Does not work with ServiceStack.Text v5

### ISSUE THREAD

**Issue by paya-cz** [Chatham/ServiceStack.Text.EnumMemberSerializer#2]
When I use ServiceStack.Text v5, it throws the following error on .Configure:

> System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
> 
> FileLoadException: Could not load file or assembly 'ServiceStack.Text, Version=3.9.44.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by AnthonyCarl** [comment]
The library has been updated to work with ServiceStack.Text v5.
